version: "3.3"

services:
  rodrigo-landing:
    image: rodrigo-landing
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.services.${SERVICE}.loadbalancer.server.port=80
        - traefik.http.routers.${SERVICE}-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.${SERVICE}-http.entrypoints=http
        - traefik.http.routers.${SERVICE}-http.middlewares=https-redirect
        - traefik.http.routers.${SERVICE}-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.${SERVICE}-https.entrypoints=https
        - traefik.http.routers.${SERVICE}-https.tls=true
        - traefik.http.routers.${SERVICE}-https.tls.certresolver=le
        - traefik.http.routers.${SERVICE}-http-www.rule=Host(`www.${DOMAIN?Variable not set}`)
        - traefik.http.routers.${SERVICE}-http-www.entrypoints=http
        - traefik.http.routers.${SERVICE}-http-www.middlewares=https-redirect
        - traefik.http.routers.${SERVICE}-https-www.rule=Host(`www.${DOMAIN?Variable not set}`)
        - traefik.http.routers.${SERVICE}-https-www.entrypoints=https
        - traefik.http.routers.${SERVICE}-https-www.middlewares=${SERVICE}-https-www
        - traefik.http.routers.${SERVICE}-https-www.tls=true
        - traefik.http.routers.${SERVICE}-https-www.tls.certresolver=le
        - traefik.http.middlewares.${SERVICE}-https-www.redirectregex.regex=^https?://www.(.*)
        - traefik.http.middlewares.${SERVICE}-https-www.redirectregex.replacement=https://$${1}
        - traefik.http.middlewares.${SERVICE}-https-www.redirectregex.permanent=true

networks:
  traefik-public:
    external: true
